name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.0.2
homepage: https://github.com/mortezaom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter


environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
